name: kelompok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  assets: ^0.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/home.jpg
    - assets/lonceng.png
    - assets/profil.jpg
    - assets/koin.png
    - assets/home1.jpg
    - assets/home2.jpg
    - assets/home3.jpg
    - assets/machiato.jpg

